# Generated by Django 5.0.2 on 2024-02-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                (
                    "price_list",
                    models.IntegerField(choices=[(1, "selling"), (2, "buying")]),
                ),
                ("price_list_rate", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
            bases=("api.basemodel",),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.basemodel",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("item_code", models.CharField(max_length=255)),
                ("price_list", models.ManyToManyField(to="api.pricelist")),
            ],
            options={
                "abstract": False,
            },
            bases=("api.basemodel",),
        ),
    ]
